Помощь друга
htmlacademy-javascript/251399-kekstagram-28 pull request #10
Opened 2023-03-28 14:09 UTC by Pifan91

2023-03-28 15:37 UTC, o-bender requested changes

2023-03-28 15:37 UTC, o-bender commented on js/upload-form.js
> +  if (value !== 'none') {
Так лучше не делать:
1. 0, 1, 1, 0.1 вообще непонятные цифры.
2. Повторы вызовов createImageEffectSlider
3. параметры эффектов и имена эффектов захардкожены в несколько функций, сложно редактировать, сложно добавлять новый эффект.

2023-03-28 15:37 UTC, o-bender commented on js/upload-form.js
> +  if (evt.target === imageUploadScaleSmaller && currentScale > 0) {
Мб стоит просто установить отдельно слушатели для каждой кнопке? Зачем такие сложности с target? Мб какие-то есть плюсы в этом решении, которые я упускаю?

2023-03-28 15:37 UTC, o-bender commented on js/upload-form.js
> +      to: function (value) {
Это копипаста из примера. Следует использовать стрелочные функции. И в идеале тернарный оператор.

2023-03-28 15:37 UTC, o-bender commented on js/upload-form.js
> +    if (effect === 'chrome') {
Повторение хардкода имён эффектов. Вне зависимости от выбранного эффекта будут произведены все проверки. Это избыточно.

2023-03-28 15:37 UTC, o-bender commented on js/upload-form.js
> +  imageUploadScaleValue.value = `${SCALE_DEFAULT} % `;
лишний пробел перед и после знака %

2023-03-28 15:37 UTC, o-bender commented on js/upload-form.js
> +  imageUploadEffectButtons.forEach((button) => {
А зачем мы каждый раз переустанавливаем и удаляем слушатели? Кнопки создаются один раз при открытии сайта. И в процессе работа не изменяются.

2023-03-29 11:10 UTC, Pifan91 commented on js/upload-form.js
> +  if (value !== 'none') {
Да, нагородил я конечно.

Переделал на работу через словарь.

2023-03-29 11:11 UTC, Pifan91 commented on js/upload-form.js
> +  if (evt.target === imageUploadScaleSmaller && currentScale > 0) {
Слушатели на каждой кнопке есть, просто хотелось всё в 1 функцию уместить.
Сейчас переделал на 2 разных

2023-03-30 08:24 UTC, merged